var PostConstants = {
  POSTS_RECEIVED: "POSTS_RECEIVED",
  POST_RECEIVED: "POST_RECEIVED",
  COMMENT_RECEIVED: "COMMENT_RECEIVED",
  COMMENT_DELETED: "COMMENT_DELETED"
};

module.exports = PostConstants;
