var PostConstants = {
  POSTS_RECEIVED: "POSTS_RECEIVED",
  POST_RECEIVED: "POST_RECEIVED",
  COMMENT_RECEIVED: "COMMENT_RECEIVED",
  COMMENT_DELETED: "COMMENT_DELETED",
  LIKE_RECEIVED: "LIKE_RECEIVED",
  LIKE_DELETED: "LIKE_DELETED",
  POST_DELETED: "POST_DELETED"
};

export default PostConstants;
