var UserConstants = {
  USER_RECEIVED: "USER_RECEIVED",
  USERS_RECEIVED: "USERS_RECEIVED",
  FOLLOW_RECEIVED: "FOLLOW_RECEIVED",
  FOLLOW_DELETED: "FOLLOW_DELETED"
};

module.exports = UserConstants;
