var UserConstants = {
  USER_RECEIVED: "USER_RECEIVED",
  USERS_RECEIVED: "USERS_RECEIVED",
  FOLLOW_RECEIVED: "FOLLOW_RECEIVED",
  FOLLOW_DELETED: "FOLLOW_DELETED",
  RESULTS_RECEIVED: "RESULTS_RECEIVED"
};

module.exports = UserConstants;
